#!/usr/local/bin/bash

# after-notes: compose component notes to list as comments following the program

error() { printf "%s\n"; exit 1; } 
shopt -s nocasematch nullglob

[[ -n $BUILD_NO_NOTES ]] && return

ob=.
test -n "$1" && ob="$1"

## resolve search directories
resolve_search_paths() {
    # if target (^ or .^) resolves as a directory, it's a prototype:
    test -d "$1" || {
        # otherwise, if it exists as a link it's a thinobject type:
        test -L "$1" && return 0
        return 1
        }
    search_paths+=("$1")
    # recurse to follow $1/^ or $1/.^ links:
    resolve_search_paths $1/^ || resolve_search_paths $1/.^ || return 1
    }
declare -a search_paths
resolve_search_paths $ob

resolve_attr() {
    for attr in "${search_paths[@]}"; do
        attr+=/$1
        test -e $attr && return 
    done
    return 1
    }

resolve_attr @order || error "no @order file found"
order=$attr

for component in $(<$order); do
    resolve_attr "$component" || continue
    for notes in $attr/@after-notes; do
        [[ -e $notes ]] || continue
        printf "\n"
        printf "' ***** %s *****\n" "$attr"
        printf "' \n"
        awk '{print "X ", $0}' $notes | sed "s/^X/'/"
    done
done

