#!/usr/local/bin/bash

error() { printf "%s\n"; exit 1; } 

resolve_search_paths() {
    # if target (^ or .^) resolves as a directory, it's a prototype:
    test -d "$1" || {
        # otherwise, if it exists as a link it's a thinobject type:
        test -L "$1" && return 0
        return 1
        }
    search_paths+=("$1")
    # recurse to follow $1/^ or $1/.^ links:
    resolve_search_paths $1/^ || resolve_search_paths $1/.^ || return 1
    }

resolve_attr() {
    for attr in "${search_paths[@]}"; do
        attr+=/$1
        test -e $attr && return 
    done
    return 1
    }

main() {

    shopt -s nocasematch nullglob
    
    declare site
    site="$1" && shift
    [[ -n $site ]] || site=.
    [[ -e $site ]] || error "$site not found"

    declare -a search_paths
    resolve_search_paths $site

    resolve_attr @order || error "no @order file found"
    order=$attr
    
    declare -a components=("$@")
    
    
    (( ${#components[@]} == 0 )) && {
        # if no components are given on command line, look for @order file
    
    }

    declare -a chunks
    chunks=(
        constants
        globals
        datatables
        functions
        subs
        programs
    )
    
    for chunk in "${chunks[@]}"; do  
        echo $chunk $site "$@"
    done
}

main "$@"

