#!/usr/local/bin/bash

error() { printf "%s\n" "$@"; exit 1; }

main() {
    local site
    local -a chunks

    export BUILD_SHOW_ID=
    while [[ ${1:1:1} == "-" ]]; do
        case "$1" in
        --show-id | --show-ids) export BUILD_SHOW_ID=1 ;;
        *)                      error "unknown option: $1" ;;
        esac
        shift
    done

    site="$1" && shift

    chunks=(
        constants-table
        constants
        globals
        datatables
        functions
        subs
        programs
    )
    
    for chunk in "${chunks[@]}"; do  
        $chunk $site "$@"
    done
}

main "$@"

