#!/usr/local/bin/bash

site=$1

test -n "$2" || {
    build $site | awk '{printf("%s\r\n",$0)}'
    exit
    }

prog=$2

dir=${prog%/*}
test -n "$dir" || dir=.
test "$dir" = "$prog" && dir=.

build $site | awk '{printf("%s\r\n",$0)}' > $prog

sig=($(csi-signature $prog))

printf "<%s>\n" "$sig"

ln -sf "=$sig" $dir/progsig
