#!/usr/local/bin/bash

# functions: compose functions for final program 

error() { printf "%s\n"; exit 1; } 
shopt -s nocasematch nullglob

ob=.
test -n "$1" && ob="$1"

## resolve search directories
resolve_search_paths() {
    # if target (^ or .^) resolves as a directory, it's a prototype:
    test -d "$1" || {
        # otherwise, if it exists as a link it's a thinobject type:
        test -L "$1" && return 0
        return 1
        }
    search_paths+=("$1")
    # recurse to follow $1/^ or $1/.^ links:
    resolve_search_paths $1/^ || resolve_search_paths $1/.^ || return 1
    }
declare -a search_paths
resolve_search_paths $ob

resolve_attr() {
    for attr in "${search_paths[@]}"; do
        attr+=/$1
        test -e $attr && return 
    done
    return 1
    }

resolve_attr @order || error "no @order file found"
order=$attr

for component in $(<$order); do
    resolve_attr "$component" || continue
    for function in $attr/@function:*; do
        name=${function##*:}
        printf "\n"
        [[ -z "$BUILD_OMIT_ID" ]] && 
            printf "' %s:%s()\n" "$component" "$name"
        cat $function
    done
done

