#!/usr/local/bin/bash

# programs: compose component program chunks into final program 

warn() { printf "%s\n" "$@" >&2; } 
error() { warn "$@"; exit 1; } 
shopt -s nocasematch nullglob

ob=.
test -n "$1" && ob="$1"

## resolve search directories
resolve_search_paths() {
    # if target (^ or .^) resolves as a directory, it's a prototype:
    test -d "$1" || {
        # otherwise, if it exists as a link it's a thinobject type:
        test -L "$1" && return 0
        return 1
    }
    search_paths+=("$1")
    # recurse to follow $1/^ or $1/.^ links:
    resolve_search_paths $1/^ || resolve_search_paths $1/.^ || return 1
}
declare -a search_paths
resolve_search_paths $ob

resolve_attr() {
    for attr in "${search_paths[@]}"; do
        attr+=/$1
        test -e $attr && return 
    done
    return 1
}

resolve_attr @order || error "no @order file found"
order=$attr

resolve_symvar() {
    for attr in "${search_paths[@]}"; do
        attr+=/$1
        test -L $attr && test ! -e $attr && return 
    done
    return 1
}

reduce_params() {
    ## in global var line, reduce {{TAG,VAL}} to params[TAG] or VAL
    local buf="$line" tag val
    line="${buf%%{{*}"
    buf="${buf#*{{}"
    ## return FALSE if no parameter substituion is needed
    [[ "$line" == "$buf" ]] && return 1
    tag="${buf%%:*}"
    buf="${buf#*:}"
    val="${buf%%\}\}*}"
    buf="${buf#*\}\}}"
    line+="${params[$tag]-$val}$buf"
    # recurse until no more expansion remain:
    reduce_params "$line" || return 0
}

# store each scan value in the scans array:
declare scan
declare -a scans
scans=()

# store data for each scan in the s associative array;
# - s[P] stores the number of lines stored for scan P
# - s[P.M] stores line M of scan P
declare -A s
s=()

declare -i n

# store patterns for regex matching
declare -A pat
pat[beginprog]="^ *beginprog"
pat[endprog]="^ *endprog"
pat[scan]="^ *scan *\("
pat[nextscan]="^ *nextscan"
pat[calltable]="^ *calltable"

declare component_object
for component in $(<$order); do
    resolve_attr "$component" || continue
    component_object="$attr"

    declare -A params
    if resolve_symvar ${component}:; then
        for param in $(symvar $attr); do
            params[${param%:*}]=${param#*:}
        done
    fi

    for file in $component_object/@prog:*; do
        scan="${file#*/@prog:}"

        # s[scan] is the number of lines already stored
        n=${s[$scan]}

        ((n==0)) && scans+=($scan)

        [[ -n $BUILD_SHOW_ID ]] && {
            n+=1
            s[$scan.$n]="        ' $component:"
        }

        while IFS= read -r line; do
          reduce_params "$line"

          # printf "$line\r\n"

            [[ "$line" =~ ${pat[beginprog]} ]] && continue
            [[ "$line" =~ ${pat[endprog]} ]] && continue
            [[ "$line" =~ ${pat[scan]} ]] && continue
            [[ "$line" =~ ${pat[nextscan]} ]] && {
                s[$scan]=$n
                continue
            }

            # accumulate entries for the final table:
            n+=1
            s[$scan.$n]="$line"
            s[$scan]=$n

        done < $file
        n+=1
        s[$scan.$n]="    "
        s[$scan]=$n

    done

done

# check the number of scan intervals to output to the program:
((${#scans[@]}>4)) && error "too many scan intervals: ${#scans[@]}"

printf "beginProg\r\n"

# output init code first!
[[ -n ${scans[init]} ]] && {
    scan=init
    for (( n=1; n<=${s[$scan]-0}; n+=1 )); do
        line="${s[$scan.$n]}"
        printf "%s\r\n" "$line"
    done
}

declare -a scan_order

if resolve_symvar scan-order; then
    scan_order=( $(symvar $attr) )
else    
    scan_order=( ${scans[*]} )
fi

# output each scan, but skip init (which could be out of order)
declare -i slowseq
for scan in "${scan_order[@]}"; do
    [[ $scan == init ]] && continue
  # printf "DEBUG  %s: %s\r\n" "$scan" "${s[scan]}"

    ((slowseq>0)) && printf "    slowSequence\r\n"

    printf "    scan(%s,sec,0,0)\r\n" $scan
    
  # printf "DEBUG:\t<%s>\r\n" "${s[@]}"
    for (( n=1; n<=${s[$scan]-0}; n+=1 )); do
        line="${s[$scan.$n]}"
        printf "%s\r\n" "$line"
    done

    printf "    nextScan\r\n"
    printf "\r\n"
    slowseq+=1
done

printf "endProg\r\n"
